[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
tun = "0.7.11"
tun-tap = "0.1.4"
tun-tap-mac = "0.1.2"
